### ISSUE TITLE
AntiTCC

### ISSUE THREAD

**Issue by hvownij** [alexstrout/foxWSFix-UT2k4#2]
Is there a way to make this compatible with Antitcc?  Currently any antitcc server will kick you for using this mod due to the GUIController it uses.

I have fixed my servers and let a few other admins know how to fix it.  but would be nice to know if this is possible. 

delete this if not in scope of what you are doing.  Thanks.

**Comment by alexstrout** [comment]
Interesting - it's probably worth noting that the GUIController override isn't actually necessary, it's only to enable menu configuration of FOV and aspect-corrected mouse sensitivity. This could be disabled by keeping the vanilla GUIController and ensuring that `bCorrectMouseSensitivity=false` in the ini (FOV could still be set in-game via `SetFOV` command).

How is this fixed on the server? Is there a whitelist mechanism for adding specific packages?

**Comment by hvownij** [comment]
So currently because it is a GUIController that is switched, antitcc does not allow those changes.  We have currently used a work around to allow the fix on most of the North American servers that use antitcc.  it just sends a message that a unknown guicontroller is in use, whitelist works for the rest.

I am not sure how this could be fixed with antitcc just figured it should be looked into.

If we are to revert and take off the GUIController, could you provide the calculations that are used to maintain the 4:3 FOV and the 4:3 mouse sens?  this would be vital and very helpful if we are to go that route.

**Comment by alexstrout** [comment]
I've pushed a commit which should hopefully solve the issue, while leaving menu functionality intact: a3ffefd3

A pre-release build is here: https://github.com/alexstrout/foxWSFix-UT2k4/releases/tag/v2.1.0-RC1
Would you mind testing this out and letting me know if the issue persists?

Thanks!

**Comment by hvownij** [comment]
Hey there!  Just wanted to report that this does solve that issue.  and for what ever reason it appears to also have solved the UTComp bug with the HUD.

**Comment by alexstrout** [comment]
Totally spaced on properly releasing 2.1 - which is now out, and identical to the test published last month. Closing this issue accordingly, but feel free to re-open if something comes up with AntiTCC again. Thanks for the report!
