### ISSUE TITLE
Distortion on FOV

### ISSUE THREAD

**Issue by blasterspike** [alexstrout/foxWSFix-UT2k4#3]
Hi,
First of all thank you for all the hard work that you have put into this!

I'm testing this on a 3840x1600 resolution and the SetRes is working perfectly.
However I'm having trouble understanding how the FOV should work.
Following the calculations on this tool
https://www.wsgf.org/fovcalc.php
I should set the FOV to 121.89 with
SetFOV 121.89
however the image on the both sides is very distorted and it is disturbing to watch after a minute.
I have tried even to lower it but the only FOV where I don't see the distortion in the default of 90.
Am I misunderstanding something?

Thanks!

**Comment by alexstrout** [comment]
Hey! So the mod actually does this calculation for you, meaning a SetFOV value of 90 would equal 90 degrees @ 4:3, or 121.89 @ 12:5. This was done figuring most players would know their comfortable (horizontal) 4:3 FOV value. Hope this helps!

**Comment by blasterspike** [comment]
Thank you for your reply!
It is still not clear to me. How did you calculate that a FOV of 121.89 is for a ratio of 12:5 and not 21:10?
So the fact that I see distortions on the left and right is because I have set a wrong FOV?

**Comment by alexstrout** [comment]
Sorry for the late response! I got the 12:5 ratio as 3840/1600 = 12/5 (or 2.4). The mod calculates this ratio in a similar way and sets the FOV accordingly. If you do "SetFOV 90" in the game, your _actual_ fov should be 121.89 (or something close to that).

**Comment by blasterspike** [comment]
Thanks for the explanation, now I get it!
It is the mod that automatically sets it to the correct FOV accordingly to the resolution, so that a `SetFOV 90` is sufficient for me.
Thank you very much for your helpfulness!
