### ISSUE TITLE
critical error when joining a match

### ISSUE THREAD

**Issue by liPillON** [alexstrout/foxWSFix-UT2k4#4]
Hi, I've just discovered this new version of the mod/fix and I've tried it in my UT2004 setup.

After configuring it as suggested in the mod readme, all seems to work just fine: the game launches, I'm able to use SetRes and SetFov to change those settings, I'm able to navigate the game menu and launch a match. The engine loads the map and then the game asks me to click FIRE to join the match.
Unfortunately, the game does not seem to receive any input from my keyboard/mouse and keep waiting for me to join the match.
As soon as I hit "ESC" to go back to the game gui/menu, a critical error popup shows up and the game crashes.

This happens in both Instant Actions and SP Ladder matches.
I have not been able to try it in multiplayer yet.

I'm running v3369 and I'm able to play just fine if I revert the InputClass setting to the default class.
The mod version I'm using is 2.1.0

This is the message that appears in the "critical error" dialog box:
```
UT2004 Build UT2004_Build_[2005-11-23_16.22]

OS: Windows NT 6.2 (Build: 9200)

CPU: GenuineIntel PentiumPro-class processor @ 1992 MHz with 2047MB RAM

Video: Intel(R) UHD Graphics 620 (8681)

General protection fault!

History: AbsorbedPaused <- ULevel::Tick <- (NetMode=0) <- TickLevel <- UGameEngine::Tick <- Level Albatross <- UpdateWorld <- MainLoop <- FMallocWindows::Free <- FMallocWindows::Realloc <- 10910191 0 FArray <- FArray::Realloc <- 0*2 <- FMallocWindows::Free
```

I'll attach my settings and logs files for both the vanilla and the modded installation.
The latter includes a dump file as well.

[logs-vanilla.zip](https://github.com/alexstrout/foxWSFix-UT2k4/files/6124814/logs-vanilla.zip)
[logs-FoxWSFix.zip](https://github.com/alexstrout/foxWSFix-UT2k4/files/6124818/logs-FoxWSFix.zip)

**Comment by liPillON** [comment]
The same issue is present when using version 2.0
Version 1.1.1 is unaffected.

**Comment by liPillON** [comment]
I've found the solution on the mod's page over @steam
https://steamcommunity.com/app/13230/discussions/0/611702631218438023/#c2995421083777573206

Basically the setting "InputClass=Class'foxWSFix.foxPlayerInput'" NEED to appear TWO times in USER.INI 
The first goes under the already suggested section "[Engine.PlayerController]" 
The second goes under the "[UnrealGame.UnrealPlayer]" section

@alexstrout you may want to update the mod's readme and make this requirement more explicit

Thanks, by the way! And keep up the good work!

**Comment by alexstrout** [comment]
Glad you got it figured out! Thanks for the detailed report with logs.

I'll try to see if I can reproduce this - I'll leave this open in the meantime.

**Comment by alexstrout** [comment]
I've updated the readme and implemented a minor failsafe in the code that should hopefully alleviate this issue (see #6 ) - feel free to re-open should this strike again. Thanks!
