### ISSUE TITLE
"foxWSFix breaks the game"

### ISSUE THREAD

**Issue by Keith94** [alexstrout/foxWSFix-UT2k4#6]
>A word of warning, while this article recommends foxWSFix, the latest version of it on the latest Steam version on Windows 10, it will stop most inputs from working when a game starts and cause a crash to desktop after a few seconds.

[Source](https://www.pcgamingwiki.com/wiki/Topic:Wabp2t4zgnja54eu)

I didn't experience this but thought I'd post it here.

**Comment by gabrielmagno** [comment]
I'm running UT2004 from Steam (Version ID 252075) on Windows 10.

After applying foxWSFix (v2.1.0), the game starts correctly, but the mouse click in some screens do not work. 

For instance, using the menu works (I can click and select options). But these 2 things fails:
 - skipping the NVIDIA logo intro animation when the game starts (mouse click will not skip, only pressing ESC button)
 - when starting a match, it asks to [FIRE] to start it, but I keep mouse-clicking and the match never starts, and eventually the game crashes.

**Comment by alexstrout** [comment]
Thanks for the report - I suspect this is related to https://github.com/alexstrout/foxWSFix-UT2k4/issues/4 and affects more people than I first thought.

It's possible the Steam version does things differently than retail / GOG (which this was originally developed / updated on, respectively), but it's likely something weird with the GUI override that I missed in testing.

**Comment by gabrielmagno** [comment]
Not sure if exactly the same issue, but I was having problems with my Steam version, and this fixed the iasues for me: 

> Basically the setting "InputClass=Class'foxWSFix.foxPlayerInput'" NEED to appear TWO times in USER.INI
> The first goes under the already suggested section "[Engine.PlayerController]"
> The second goes under the "[UnrealGame.UnrealPlayer]" section

Source: https://github.com/alexstrout/foxWSFix-UT2k4/issues/4#issuecomment-797092675

**Comment by alexstrout** [comment]
I couldn't quite replicate the crash, but I could replicate the loss of control if both `UnrealGame.UnrealPlayer` and `XGame.xPlayer` didn't have an InputClass line set. Note that the hierarchy in-game is `PlayerController -> UnrealPlayer -> xPlayer`, so whatever's set latest will take precedence. In the main menu, only `PlayerController` is used.

The latest v2.1.1 release should hopefully alleviate this issue - at the very least, it will log some useful information on-screen / to the console if something's not quite set up right. If it's a missing InputClass line, it will attempt to automatically remedy it. I've also updated the install instructions in the readme to reflect the above.

Please let me know if anyone still runs into issues with this. Thanks!
